"""Module for managing graph parameters."""
GRAPH_PARAMETER = {
    "TOP_ENTITIES": 5,
	"ENTITIES_DISTANCE_THRESHOLD": 0.5,
    "TOP_TRIPLES": 10,
    "TOP_MERGED_TRIPLES": 15,
	"TRIPLES_DISTANCE_THRESHOLD": 1.2,
	
    "TOP_ENTITIES_FALLBACK": 15,
	"ENTITIES_DISTANCE_THRESHOLD_FALLBACK": 0.5,
    "TOP_TRIPLES_FALLBACK": 15,
    "TOP_MERGED_TRIPLES_FALLBACK": 15,
	"TRIPLES_DISTANCE_THRESHOLD_FALLBACK": 1.2,
	
    #"TOP_CHUNKS": 5,
    #"TOP_COMMUNITIES": 3,
    #"TOP_OUTGOING_RELATIONSHIPS": 5,
    #"TOP_INCOMING_RELATIONSHIPS": 5
}
